### ISSUE TITLE
Citizen setting is broken.

### ISSUE THREAD

**Issue by Spacemanspark** [Yonaguni/EuropaStation#147] opened 2015-08-23 22:38 UTC
In occupation preferences, clicking citizen locks up the occupation options. It turns all the jobs yellow and there are no options next to them. It's easy to temporarily fix this by pressing the 'reset' button and picking something else.

**Comment by PsiOmegaDelta** [comment] 2015-08-24 06:45
Duplicate of #106.

**Closed** 2015-08-24 07:56 UTC
